// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCaJtKLjYZdSvBUgBhgky1IrFxqtZLI0',
    appId: '1:226463724050:web:69761e212767df42985ecb',
    messagingSenderId: '226463724050',
    projectId: 'auth-firebase-16c30',
    authDomain: 'auth-firebase-16c30.firebaseapp.com',
    storageBucket: 'auth-firebase-16c30.appspot.com',
    measurementId: 'G-RVGXRHP10K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBu9f-lHiit71qCHXOjlQyToHVvNg3n0',
    appId: '1:226463724050:android:fae3811ba6e27aa5985ecb',
    messagingSenderId: '226463724050',
    projectId: 'auth-firebase-16c30',
    storageBucket: 'auth-firebase-16c30.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNCaJtKLjYZdSvBUgBhgky1IrFxqtZLI0',
    appId: '1:226463724050:web:b5095a0a158bacfc985ecb',
    messagingSenderId: '226463724050',
    projectId: 'auth-firebase-16c30',
    authDomain: 'auth-firebase-16c30.firebaseapp.com',
    storageBucket: 'auth-firebase-16c30.appspot.com',
    measurementId: 'G-LWBSFBP3MV',
  );
}
